### ISSUE TITLE
How do I add data source into grafana?

### ISSUE THREAD

**Issue by yanhongwang** [johrstrom/jmeter-prometheus-plugin#35]
Hello,

My environment condition:
Linux Mint: 19
JMeter: 5.0
Grafana: v5.3.2 (0d821d0)

I can retrieve output data from http://localhost:9270/metrics when running pressure loading.

But, when I add http://localhost:9270 to Grafana to be one of 'Data Sources'. That seem can't be detected well. That will keep show 'Exclamation mark'.

So even thought I import 'JMeter.json' into Grafana, I still can't see Grafana normal behavioral when I do load test. Is that also happen to you?

Thanks.

**Comment by johrstrom** [comment]
This is a promethues exporter. Data goea only as far as prometheus.

This is the data flow:
jmeter -> prometheus

If you need grafana help for 'how to connect to prometheus' consult grafana documentation.

Also consult prometheus documentation so that you can configure prometheus to scrape from your jmeter instance running this plugin.


I hope thats helpful.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by yanhongwang** [comment]
Hello @johrstrom ,

Thanks for your hint.
I thought Prometheus and JMeter are individually add into Grafana.
And thanks for your explanation.

Could you please provide **JMeter configuration** in prometheus.yml?
Is that also available run in **Kubernetes**?

Thanks very much!

**Comment by johrstrom** [comment]
I cannot especially eith questions of where ur instances run, that ur topology is.

Again consult prometheus docs. I would look specifically at 'static targets'.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------
