### ISSUE TITLE
additional configurations

### ISSUE THREAD

**Issue by paulwhitehead74** [johrstrom/jmeter-prometheus-plugin#36]
Would be useful to provide additional percentiles 90 and 95th along with 99th. Can this be obtain via update of this plugin code or would there need to be any additional changes jmeter side. By default jmeter backend listener by default expose 90, 95 and 99th.

**Comment by johrstrom** [comment]
Yes, i was working on a branch to allow users to define anything. But the code is so kludgey and i never got back to it.

This plugin should allow for that configuration, there's nothing needed on the jmeter side.




-------- Original message --------

**Comment by kvanderhoek** [comment]
+1 for this feature

**Comment by johrstrom** [comment]
Thanks for that additional example of influx DB.   Let's use this ticket for discussion and I'll close the other as duplicate because really what this is about being highly configurable. 

As I'd said, the code is kludgey because I [implemented the wrong abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction), but here's what it looks like.  What do you think?   It looks like the influxDB plugin you only get one metric per listener?  I don't like that, because you may end up created 5 or more listeners to capture every metric. One consideration for this thinking is not only the performance testing use case, but the functional (counters for failures/response codes or assertions on the body of the response). 

I'm trying to motivate myself to finish this and now that the holidays are over I might just.

![image](https://user-images.githubusercontent.com/4874123/51640465-6541d480-1f18-11e9-9b02-9c4856ed0f0a.png)

**Comment by johrstrom** [comment]
@kvanderhoek @paulwhitehead74  what do you think of that UI layout?  I'm of the mind it should be as configurable as possible.  Note that I'm allowing for complete metric customization, which I can understand may be a bit much from a user's perspective. But OSS is all about 'create configuration, not policy'.  This ticket is about not forcing policy on users and this UI layout is my 

I've implemented "Measuring Response time" on the release-0.1.0-revised branch. You can check it out for yourself.  Response time can only be a histogram or summary.

**Comment by paulwhitehead74** [comment]
That looks good johrstrom. Happy to test once it's in a good state. Thanks

**Comment by johrstrom** [comment]
The branch is ready with some decent documentation and an example.  Only response times can be measured with it. This week I'll release it as jar (version 0.2.0-rc1) but if you want to pull and build it now to see you can. 

https://github.com/johrstrom/jmeter-prometheus-plugin/tree/release-0.1.0-revised

**Comment by johrstrom** [comment]
Tagged and released. https://github.com/johrstrom/jmeter-prometheus-plugin/releases/tag/0.2.0-rc1 

https://github.com/johrstrom/jmeter-prometheus-plugin/issues/40 is the only bug I see.

**Comment by johrstrom** [comment]
I have been releasing several jars.  Most recently 0.2.0-rc3. This version has all the functionality of measuring samples.

**Comment by johrstrom** [comment]
@kvanderhoek  and @paulwhitehead74 I'll be closing this ticket soon given the progress & releases, but I'm happy to hear feedback.

cc: @GiovanniPaoloGibilisco @var23rav @chiabre I know it's kind of out of context for you guys, but you may or may not have noticed the major re-factor I've done to this library.  I'd appreciate any feedback you guys may have on the UI/usability/whatever and the direction I've taken.

**Comment by johrstrom** [comment]
I'm closing this ticket, but anyone on this thread (or just in general) can re-open to continue the discussion for any reason.
