### ISSUE TITLE
What does the `jsr223` mean?

### ISSUE THREAD

**Issue by Germey** [johrstrom/jmeter-prometheus-plugin#77]
I want to change the metrics name because I'm confused about the name `jsr223`, could you tell me its meaning?

Why not call it `jmeter-prometheus` or `jp***`?

**Comment by johrstrom** [comment]
Are you talking about the metrics in the docs?  I used the `jsr223` because the metrics are from a [jsr223 sampler](https://jmeter.apache.org/usermanual/component_reference.html#JSR223_Sampler).  I wanted the example to "just work" without having to hit google or something else that would need the internet. 

You can name metrics whatever you like in your test like `http_` or `that_thing_im_testing_` there are [prometheus docs here](https://prometheus.io/docs/practices/naming/) on it, but the prefix should just be meaningful.  In this case, it indicates the type of sampler they're coming from.

And just as an FYI I think jsr223 is java service request 223 for the addition of scripting languages into the java language.  In any case, I think the link to the jmeter docs is more insightful on that.

Hope that helps!

**Comment by GiovanniPaoloGibilisco** [comment]
@Germey do you think that this #73 would help?
If you think other names for default metrics could be more readable leave a comment there.
